### ISSUE TITLE
[Question] Regarding "Negative Prompt"

### ISSUE THREAD

**Issue by waredrive** [artisticMink/anlatan-nai-extras#25]
Let me start by thanking you for your work. I'm curious about the functionality of the native 'Negative Prompt' feature in SillyTavern. Is it supported when using your extension?

**Comment by artisticMink** [comment]
I know NAI supports banned tokens but i'm not sure to what extend NAI supports negative prompting. If it's part of the NAI interface in ST, it should work. NAI Extras tampers with the context but does not significantly alter any other options sent to NAI by ST.
