### ISSUE TITLE
Chat Start?

### ISSUE THREAD

**Issue by privatesvx** [artisticMink/anlatan-nai-extras#26]
Shouldn't the Chat Start instruction be sent before a {{chat}}? I mean that option which is next to the example separator. 

Should I add it manually in Chat Format or it's not neccessary?

**Comment by artisticMink** [comment]
What do you mean with `chat start instruction`?

**Comment by artisticMink** [comment]
If you mean `***`, this is a dinkus. You can read more about it here: https://docs.novelai.net/text/specialsymbols.html

It implies the start of a new scene. Placing it after {{chat}} would tell the model that the chat happened, but that it's now time for a new scene.
